### PR TITLE
Bramble nodes

### PR DESCRIPTION
**Pull request by FreezeDriedMangos**
### What's new?

- bramble dimensions and connected nodes/seeds can now be created using the Bramble module
- specifying Bramble.dimension turns the body into a bramble dimension rather than a planet
- bramble dimension bodies must have Orbit.staticPosition specified (and it should be some crazy value with xyz all in the range of 3k-10k)
- to be able to exit a dimension, you must have a node somewhere with a name specified. Use this name to link it to the dimension as an exit
- placing a signal inside a dimension automatically adds that signal to that dimension's direct entrance nodes! 
    - note: if you have a dimension with its entrance node inside another dimension, that second dimension's entrance nodes will not have the original dimension's signals

### CODE REVIEW

**Comment by xen-42** [comment]
What if we do make the signals keep going? Just repeat whatever you're doing the first time on all dimensions over and over until it stops adding new signals

**Comment by xen-42** [comment]
Also does the scout signal work in custom dimensions?

**Comment by xen-42** [comment]
Also also do we have the mini nodes set up? Like the small seeds that only your scout can fit through.

**Comment by FreezeDriedMangos** [comment]
> Also also do we have the mini nodes set up? Like the small seeds that only your scout can fit through.

Yep! You can make them using the "isSeed" property

> Also does the scout signal work in custom dimensions?

Yep. 

That does bring up another issue though - I can't figure out how to make signals display as "ERROR - Duplicate Signal". I'm thinking of not adding support for that anyway though because it would be complicated to figure out when that should display. For example, if a dimension only has one entrance node, then the signal should not be shown as a duplicate.

**Pull request merged**
